services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: usuario
      MYSQL_DATABASE: ejercicio2Investigacion
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
    ports:
      - "3306:3306"
    networks:
      - backend_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build: ./EjercicioDocker1
    container_name: spring_backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ejercicio2Investigacion
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: usuario
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    networks:
      - backend_network

  frontend:
    build: ./angular-frontend
    container_name: angular_frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - backend_network

networks:
  backend_network:

volumes:
  mysql_data: